name: Build Docker image and deploy

on:
  push:
    branches:
      - release
    workflow_dispatch:

jobs:
  build-docker-image-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}
          submodules: true

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for Gradle wrapper(gradlew)
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar -Dspring.profiles.active=prod

      - name: Copy jar file to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./build/libs/*.jar"
          target: "/home/${{ secrets.USERNAME }}/mc-archieve-server/"

      - name: Copy docker file to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./Dockerfile"
          target: "/home/${{ secrets.USERNAME }}/mc-archieve-server/"

      - name: Copy docker compose file to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "/home/${{ secrets.USERNAME }}/mc-archieve-server/"

      - name: Run docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/${{ secrets.USERNAME }}/mc-archieve-server
            docker compose down
            docker compose -f docker-compose.yml up -d --build